
langugage: node_js

node_js: "12"

before_script: npm install -g mocha
    
jobs:
  include:
    - script: cd origin-request && npm test
      name: 'Origin Request'
    - script: cd origin-response && npm test
      name: 'Origin Response'