branches:
    only:
    - hex-arc
    
langugage: node_js

node_js: "12"

before_script:
    - npm install -g mocha
    
jobs:
    include:
        - name: 'Origin Request'
        script: cd origin-request && npm test
        - name: 'Origin Response'
        script: cd origin-response && npm test
    
